# Site settings
title: Randy Perez
tagline: "here's where you put a nice, short description of yourself!"
url: "https://randymperez13.github.io" # The base hostname & protocol for your site. Use it if you need absolute URL's
subdirectory: ""
permalink: /:title/

# Contact
# the mailto: in the email is important!
# use full links
links:
  facebook: https://facebook.com/fbusername
  twitter: https://twitter.com/twusername
  linkedin: https://linkedin.com/username
  email: mailto:cool@nice.expert

# Use this for production
#sass:
#    style: :compressed

exclude: [.scss, README.md, node_modules, gruntfile.js, package.json]
